server:
  port: 8082
#    servlet:
#        context-path: /report
# 数据源配置
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    mysql:
      jdbc-url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/report
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      validation-query: select 1
    druid:
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      jdbc-url: jdbc:hive2://127.0.0.1:10000/svc
      username: username
      password: password
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 10
      #获取连接等待超时时间
      max-wait: 60000
      connectionTimeout: 600000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最大、最小生存的时间(ms)
      max-evictable-idle-time-millis: 900000
      min-evictable-idle-time-millis: 300000
      #检测连接是否有效
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #状态监控过滤器：监控web应用的每个请求所触发的DB操作
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*
      #访问监控页面的servlet处理器
      stat-view-servlet:
        enabled: true
        #servlet url
        url-pattern: /druid/*
        #允许清空统计数据
        reset-enable: true
        #监控页面的登录名、密码
        login-username: username
        login-password: password
      #打开监控
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true

#监控
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.*: info
    org.*: info
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} [%15thread] %-5level --- %msg%n'
  file:
    name: /var/log/svc-data-sync/reports.log
