scrape_configs:
  # 可随意指定
  - job_name: 'spring-boot-test'
    # 多久采集一次数据
    scrape_interval: 15s
    # 采集时的超时时间
    scrape_timeout: 10s
    # 采集的路径
    metrics_path: '/actuator/prometheus'
    # 采集服务的地址，设置成Springboot应用所在服务器的具体地址
    static_configs:
      - targets: ['192.168.88.220:8081','192.168.88.220:8080','192.168.88.220:9002']